---
# catalog
catalog_ckan_app_version: master
catalog_ckan_archiver_process_count: 3
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_email_from: "{{ default_email_from }}"
catalog_ckan_harvest_fetch_process_count: 6
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: catalog-harvester1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_redis_password: "{{ redis_password }}"
catalog_ckan_fgdc2iso_host: catalog-fgdc2iso1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_saml2_enabled: true
catalog_ckan_service_url: https://{{ catalog_host_public }}
catalog_ckan_admin_service_url: https://{{ catalog_host_admin }}
catalog_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"
catalog_ckan_solr_port: "8983"
catalog_ckan_solr_host: datagov-solr1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_wsgi_processes: 6
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"


# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
common_ubuntu_advantage_token: "{{ vault_common_ubuntu_advantage_token }}"
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: labs.data.gov labs-bsp.data.gov dashboard-bsp.data.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://labs.data.gov/dashboard
php_cli_memory_limit: 3192M

# data.gov-wide variables
datagov_environment: production


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIILWTCCCkGgAwIBAgITHQABNI0lvrQFs7C/uQACAAE0jTANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIwMDczMTEzMDI1MVoXDTIyMTEwMzEzMDI1
  MVowge8xCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMTIwMAYDVQQDEyljYXRhbG9nLWZnZGMyaXNvMXAucHJvZC1v
  Y3NpdC5ic3AuZ3NhLmdvdjEiMCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3Nh
  LmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMGIfs+QT4FKY5J5
  F00dsPv21kzS14NBpRQEVl+MgvvyURWdcohss/E9BlKtwYmdaJm0sDMsVaoNcS2x
  KOyTIzlVbw3QJmn33646UH8X5b36upyZh3M2EP5DAocq9A+HAITt9Wppd4qC9oW3
  0IXLM9/m+AMmBVYK+ZLazwLAmC7e+Vu61xMHAYFdiHbmsI4Jp3gO9jNKy09+LuXx
  EYSJOh9pcxxR9d2H5Gjv1OPhklfUUU+mJRJtizwOjnLUVwijMULv58/Nha8MXjFS
  sgKbQuDSj27F+4PaMN65GjaaTw79xvUjHPZDzotPi7xA9w65TGzzTyStk3dr6DpG
  6yuvwX8CAwEAAaOCB2swggdnMBMGA1UdJQQMMAoGCCsGAQUFBwMBMIIFrgYDVR0R
  BIIFpTCCBaGCKWNhdGFsb2ctZmdkYzJpc28xcC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292gipjYXRhbG9nLWhhcnZlc3RlcjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aC
  KmNhdGFsb2ctaGFydmVzdGVyMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIqY2F0
  YWxvZy1oYXJ2ZXN0ZXIzcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gipjYXRhbG9n
  LWhhcnZlc3RlcjRwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNhdGFsb2ctaGFy
  dmVzdGVyNXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIqY2F0YWxvZy1oYXJ2ZXN0
  ZXI2cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRhbG9nLXdlYjFwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCJGNhdGFsb2ctd2ViMnAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIlY2F0YWxvZ2Itd2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIl
  Y2F0YWxvZ2Itd2ViMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIkY2F0YWxvZ2J3
  ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRhbG9nYndlYjJwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCKWNhdGFsb2doYXJ2ZXN0ZXIxcC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giljYXRhbG9naGFydmVzdGVyMnAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjNwLnByb2Qtb2NzaXQuYnNwLmdzYS5n
  b3aCKWNhdGFsb2doYXJ2ZXN0ZXI0cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gilj
  YXRhbG9naGFydmVzdGVyNXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxv
  Z2hhcnZlc3RlcjZwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJ2NhdGFsb2dwdWIt
  d2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoImY2F0YWxvZ3B1YndlYjFwLnBy
  b2Qtb2NzaXQuYnNwLmdzYS5nb3aCI2NhdGFsb2d3ZWIxcC5wcm9kLW9jc2l0LmJz
  cC5nc2EuZ292giNjYXRhbG9nd2ViMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIl
  ZGFzaGJvYXJkd2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIlZGFzaGJvYXJk
  d2ViMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIlZGF0YWdvdi1qdW1wMnAucHJv
  ZC1vY3NpdC5ic3AuZ3NhLmdvdoIlZGF0YWdvdi1zb2xyMXAucHJvZC1vY3NpdC5i
  c3AuZ3NhLmdvdoIlZGF0YWdvdi1zb2xyMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdv
  doImZGF0YWdvdi1zb2xybTFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCI2ludmVu
  dG9yeS0xcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giNpbnZlbnRvcnktMnAucHJv
  ZC1vY3NpdC5ic3AuZ3NhLmdvdoIiaW52ZW50b3J5MXAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIiaW52ZW50b3J5MnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIecmVk
  aXMxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giV3b3JkcHJlc3N3ZWIxcC5wcm9k
  LW9jc2l0LmJzcC5nc2EuZ292giV3b3JkcHJlc3N3ZWIycC5wcm9kLW9jc2l0LmJz
  cC5nc2EuZ292MB0GA1UdDgQWBBSWIQCqMSADS9Gl/avaXzPqbMKqbjAfBgNVHSME
  GDAWgBRJTMnw/2SFmsdiK/7LKLQoTEUiGDBMBgNVHR8ERTBDMEGgP6A9hjtodHRw
  Oi8vZ3NhcGtpLmVudC5kcy5nc2EuZ292L2dzYWNlcnRzL0VDT0gyUy1JU1NDQTAx
  KDIpLmNybDCBpwYIKwYBBQUHAQEEgZowgZcwZQYIKwYBBQUHMAKGWWh0dHA6Ly9n
  c2Fwa2kuZW50LmRzLmdzYS5nb3YvZ3NhY2VydHMvRUNPSDJTLUlTU0NBMDEuZW50
  LmRzLmdzYS5nb3ZfRUNPSDJTLUlTU0NBMDEoMikuY3J0MC4GCCsGAQUFBzABhiJo
  dHRwOi8vZ3Nhb2NzcC5lbnQuZHMuZ3NhLmdvdi9vY3NwMAsGA1UdDwQEAwIFoDA8
  BgkrBgEEAYI3FQcELzAtBiUrBgEEAYI3FQiDia8vhZ6gfYL5gw+GsI4NhJ+XET6B
  6pw1hO9mAgFkAgETMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEwDQYJKoZI
  hvcNAQELBQADggEBALgbEK7v9AP4t34bcwJrzhGexqmEP2ptAT3jZSrn3S57X5J5
  t9BSHh9FsvegFSF39Cq7LvmKIP9NhfJBx8KVg+bir0tP2uP56slaCxXMXRVCu37e
  g1fcMEF8rtWUd57E7+HLNxuvXH1/1iIQid0feMvceMOx2drH66D2LaAIezlz4CaX
  gN1A1X5/KueZ887ntc5Ei6fZas2B/Zy/3rLIS3Ce90UrLE5nGKzLflzhExDOU9J5
  5NamNMH2Mkrz9u2C1yDd71Jix05m7ApC+Qb1nNUZhd76QDKIudm3kq89bBM2Se5a
  2pREA8NteodudO5EjMaGchcFV0Hnli4xaVNkp3k=
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_production }}"


inventory_ckan_service_url: https://inventory.data.gov
inventory_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"


# New Relic
newrelic_license_key: "{{ vault_newrelic_license_key }}"


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.data.gov
pycsw_ckan_url: https://catalog.data.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"

# public urls
catalog_host_public: catalog.data.gov
catalog_host_admin: admin-catalog.data.gov

catalog_url_public: https://{{ catalog_host_public }}
catalog_url_admin: https://{{ catalog_host_admin }}

ckan_site_domain: "{{ catalog_host_public }}"

# next public urls
catalog_host_public_next: catalog-next.data.gov
catalog_host_admin_next: admin-catalog-next.data.gov


# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"


# solr
solr_master_server: datagovsolrm1p.prod-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 8192m



# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
default_email_from: "{{ vault_default_email_from }}"
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply+{{ ansible_fqdn }}@data.gov


# Redis
redis_password: "{{ vault_redis_password }}"


# SAML
saml2_idp_entry: login.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
fgdc2iso_saxon_license: "{{ vault_fgdc2iso_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# Automated CI tests
ci_inventory: inventories/production
ci_ssh_config_host: '*.prod-ocsit.bsp.gsa.gov'
ci_deploy_version: master


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: www.data.gov data.gov wp-bsp.data.gov labs.data.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://www.data.gov
