---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:
  - name: ckan-catalog-app-bionic
    image: ubuntu:bionic
    # start-stop-daemon doesn't detect tomcat is running in docker and `service
    # start/stop` fails. SYS_PTRACE is needed.
    # https://stackoverflow.com/questions/29683231/tomcat7-fail-to-start-inside-ubuntu-docker-container/29686963#29686963
    capabilities:
      - SYS_PTRACE
    groups:
      - v2
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        catalog_ckan_who_ini_secret: e45cfed3-40f1-41c0-8e92-77eda7ddd9f3
        # https://github.com/DavidWittman/ansible-redis/blob/21b0b6f9030275a2586baf591f322ce3348b2b2d/tasks/install.yml#L9
        redis_travis_ci: true
        ckan_catalog_next: true
        ckan_uses_gunicorn: true
        app_repo: https://github.com/GSA/catalog.data.gov
        app_repo_branch: enable-saml2
        ckan_production_ini_template: catalog-next/etc_ckan_production.ini.j2
        catalog_ckan_saml2_enabled: true
        ckan_who_ini_template_dir: "catalog-next"
        saml2_idp_metadata_url: "https://idp.int.identitysandbox.gov/api/saml/metadata2020"
        saml2_site_url: "https://catalog-next.sandbox.datagov.us/"
        saml2_sp_public_certificate: ""
        saml2_sp_private_key: ""
        catalog_ckan_redis_url: redis://:secret@localhost:6379/0
        catalog_ckan_plugins_default:
          - envvars
          - image_view
          - text_view
          - recline_view
          - harvest
          - geodatagov
          - datajson
          - datajson_harvest
          - geodatagov_miscs
          - z3950_harvester
          - arcgis_harvester
          - geodatagov_geoportal_harvester
          - waf_harvester_collection
          - geodatagov_csw_harvester
          - geodatagov_doc_harvester
          - geodatagov_waf_harvester
          - spatial_query
          - datagovtheme
          - saml2
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
scenario:
  name: catalog-next
  # Disable idempotence check
  # davidwittman.redis is not idempotent
  # https://github.com/DavidWittman/ansible-redis/pull/202
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
